//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CharacterInfoSoldierIcon
{
    public Label labelHp { get; private set; }

    public VisualElement panelContainer { get; private set; }

    public VisualElement Root { get; }

    public CharacterInfoSoldierIcon(VisualElement root)
    {
        Root = root;
        labelHp = Root?.Q<Label>("labelHp");
        panelContainer = Root?.Q<VisualElement>("panelContainer");
    }
}