//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CountryRulerInfo
{
    public Image imageCountryColor { get; private set; }

    public Label labelRulerTitle { get; private set; }

    public Label labelRulerName { get; private set; }

    public Label labelAreaCount { get; private set; }

    public Label labelTotalIncome { get; private set; }

    public Label labelTotalGold { get; private set; }

    public Label labelMemberCount { get; private set; }

    public Label labelSoldierCount { get; private set; }

    public Label labelTotalPower { get; private set; }

    public Image imageAllyCountryColor { get; private set; }

    public Label labelAlly { get; private set; }

    public Image imageRuler { get; private set; }

    public VisualElement Country { get; private set; }

    public VisualElement Root { get; }

    public CountryRulerInfo(VisualElement root)
    {
        Root = root;
        imageCountryColor = Root?.Q<Image>("imageCountryColor");
        labelRulerTitle = Root?.Q<Label>("labelRulerTitle");
        labelRulerName = Root?.Q<Label>("labelRulerName");
        labelAreaCount = Root?.Q<Label>("labelAreaCount");
        labelTotalIncome = Root?.Q<Label>("labelTotalIncome");
        labelTotalGold = Root?.Q<Label>("labelTotalGold");
        labelMemberCount = Root?.Q<Label>("labelMemberCount");
        labelSoldierCount = Root?.Q<Label>("labelSoldierCount");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        imageAllyCountryColor = Root?.Q<Image>("imageAllyCountryColor");
        labelAlly = Root?.Q<Label>("labelAlly");
        imageRuler = Root?.Q<Image>("imageRuler");
        Country = Root?.Q<VisualElement>("Country");
    }
}