//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class KessenMemberDefenceSide
{
    public BattleSoldierIconDefenceSide DefenderSoldier10 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier11 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier12 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier13 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier14 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier05 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier06 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier07 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier08 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier09 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier00 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier01 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier02 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier03 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier04 { get; private set; }

    public VisualElement DefenderSoldiers { get; private set; }

    public VisualElement imageDefender { get; private set; }

    public VisualElement Root { get; }

    public KessenMemberDefenceSide(VisualElement root)
    {
        Root = root;
        DefenderSoldier10 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier10"));
        DefenderSoldier11 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier11"));
        DefenderSoldier12 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier12"));
        DefenderSoldier13 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier13"));
        DefenderSoldier14 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier14"));
        DefenderSoldier05 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier05"));
        DefenderSoldier06 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier06"));
        DefenderSoldier07 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier07"));
        DefenderSoldier08 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier08"));
        DefenderSoldier09 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier09"));
        DefenderSoldier00 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier00"));
        DefenderSoldier01 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier01"));
        DefenderSoldier02 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier02"));
        DefenderSoldier03 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier03"));
        DefenderSoldier04 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier04"));
        DefenderSoldiers = Root?.Q<VisualElement>("DefenderSoldiers");
        imageDefender = Root?.Q<VisualElement>("imageDefender");
    }
}