//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class KessenWindow
{
    public Label labelAttackerNameCaption { get; private set; }

    public Label AttackerName { get; private set; }

    public Label labelDefenderNameCaption { get; private set; }

    public Label DefenderName { get; private set; }

    public KessenMemberAttackSide Attacker00 { get; private set; }

    public KessenMemberAttackSide Attacker01 { get; private set; }

    public KessenMemberAttackSide Attacker02 { get; private set; }

    public KessenMemberAttackSide Attacker03 { get; private set; }

    public KessenMemberAttackSide Attacker04 { get; private set; }

    public KessenMemberAttackSide Attacker05 { get; private set; }

    public KessenMemberAttackSide Attacker06 { get; private set; }

    public KessenMemberAttackSide Attacker07 { get; private set; }

    public KessenMemberAttackSide Attacker08 { get; private set; }

    public KessenMemberAttackSide Attacker09 { get; private set; }

    public KessenMemberDefenceSide Defender00 { get; private set; }

    public KessenMemberDefenceSide Defender01 { get; private set; }

    public KessenMemberDefenceSide Defender02 { get; private set; }

    public KessenMemberDefenceSide Defender03 { get; private set; }

    public KessenMemberDefenceSide Defender04 { get; private set; }

    public KessenMemberDefenceSide Defender05 { get; private set; }

    public KessenMemberDefenceSide Defender06 { get; private set; }

    public KessenMemberDefenceSide Defender07 { get; private set; }

    public KessenMemberDefenceSide Defender08 { get; private set; }

    public KessenMemberDefenceSide Defender09 { get; private set; }

    public Button buttonAttack { get; private set; }

    public Button buttonRetreat { get; private set; }

    public Button buttonResult { get; private set; }

    public VisualElement Root { get; }

    public KessenWindow(VisualElement root)
    {
        Root = root;
        labelAttackerNameCaption = Root?.Q<Label>("labelAttackerNameCaption");
        AttackerName = Root?.Q<Label>("AttackerName");
        labelDefenderNameCaption = Root?.Q<Label>("labelDefenderNameCaption");
        DefenderName = Root?.Q<Label>("DefenderName");
        Attacker00 = new KessenMemberAttackSide(Root?.Q<VisualElement>("Attacker00"));
        Attacker01 = new KessenMemberAttackSide(Root?.Q<VisualElement>("Attacker01"));
        Attacker02 = new KessenMemberAttackSide(Root?.Q<VisualElement>("Attacker02"));
        Attacker03 = new KessenMemberAttackSide(Root?.Q<VisualElement>("Attacker03"));
        Attacker04 = new KessenMemberAttackSide(Root?.Q<VisualElement>("Attacker04"));
        Attacker05 = new KessenMemberAttackSide(Root?.Q<VisualElement>("Attacker05"));
        Attacker06 = new KessenMemberAttackSide(Root?.Q<VisualElement>("Attacker06"));
        Attacker07 = new KessenMemberAttackSide(Root?.Q<VisualElement>("Attacker07"));
        Attacker08 = new KessenMemberAttackSide(Root?.Q<VisualElement>("Attacker08"));
        Attacker09 = new KessenMemberAttackSide(Root?.Q<VisualElement>("Attacker09"));
        Defender00 = new KessenMemberDefenceSide(Root?.Q<VisualElement>("Defender00"));
        Defender01 = new KessenMemberDefenceSide(Root?.Q<VisualElement>("Defender01"));
        Defender02 = new KessenMemberDefenceSide(Root?.Q<VisualElement>("Defender02"));
        Defender03 = new KessenMemberDefenceSide(Root?.Q<VisualElement>("Defender03"));
        Defender04 = new KessenMemberDefenceSide(Root?.Q<VisualElement>("Defender04"));
        Defender05 = new KessenMemberDefenceSide(Root?.Q<VisualElement>("Defender05"));
        Defender06 = new KessenMemberDefenceSide(Root?.Q<VisualElement>("Defender06"));
        Defender07 = new KessenMemberDefenceSide(Root?.Q<VisualElement>("Defender07"));
        Defender08 = new KessenMemberDefenceSide(Root?.Q<VisualElement>("Defender08"));
        Defender09 = new KessenMemberDefenceSide(Root?.Q<VisualElement>("Defender09"));
        buttonAttack = Root?.Q<Button>("buttonAttack");
        buttonRetreat = Root?.Q<Button>("buttonRetreat");
        buttonResult = Root?.Q<Button>("buttonResult");
    }
}