//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class KessenMemberAttackSide
{
    public BattleSoldierIconAttackSide AttackerSoldier10 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier11 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier12 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier13 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier14 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier05 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier06 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier07 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier08 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier09 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier00 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier01 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier02 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier03 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier04 { get; private set; }

    public VisualElement imageAttacker { get; private set; }

    public VisualElement AttackerSoldiers { get; private set; }

    public VisualElement Root { get; }

    public KessenMemberAttackSide(VisualElement root)
    {
        Root = root;
        AttackerSoldier10 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier10"));
        AttackerSoldier11 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier11"));
        AttackerSoldier12 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier12"));
        AttackerSoldier13 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier13"));
        AttackerSoldier14 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier14"));
        AttackerSoldier05 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier05"));
        AttackerSoldier06 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier06"));
        AttackerSoldier07 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier07"));
        AttackerSoldier08 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier08"));
        AttackerSoldier09 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier09"));
        AttackerSoldier00 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier00"));
        AttackerSoldier01 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier01"));
        AttackerSoldier02 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier02"));
        AttackerSoldier03 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier03"));
        AttackerSoldier04 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier04"));
        imageAttacker = Root?.Q<VisualElement>("imageAttacker");
        AttackerSoldiers = Root?.Q<VisualElement>("AttackerSoldiers");
    }
}