//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class MainUI
{
    [SerializeField]
    private UIDocument _document;
    public VisualElement UIContainer { get; private set; }

    public Button buttonNextPhase { get; private set; }

    public Button buttonNextTurn { get; private set; }

    public Button buttonAuto { get; private set; }

    public Button buttonHold { get; private set; }

    public Button buttonUpdateLocalization { get; private set; }

    public Button buttonToggleDebugUI { get; private set; }

    public VisualElement DebugUI { get; private set; }

    public BattleWindow BattleWindow { get; private set; }

    public WatchModeWindow WatchModeWindow { get; private set; }

    public KessenWindow KessenWindow { get; private set; }

    public SystemWindow SystemWindow { get; private set; }

    public MessageWindow MessageWindow { get; private set; }

    public VisualElement DebugUIParent { get; private set; }

    public VisualElement WindowHost { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        UIContainer = Root?.Q<VisualElement>("UIContainer");
        buttonNextPhase = Root?.Q<Button>("buttonNextPhase");
        buttonNextTurn = Root?.Q<Button>("buttonNextTurn");
        buttonAuto = Root?.Q<Button>("buttonAuto");
        buttonHold = Root?.Q<Button>("buttonHold");
        buttonUpdateLocalization = Root?.Q<Button>("buttonUpdateLocalization");
        buttonToggleDebugUI = Root?.Q<Button>("buttonToggleDebugUI");
        DebugUI = Root?.Q<VisualElement>("DebugUI");
        BattleWindow = new BattleWindow(Root?.Q<VisualElement>("BattleWindow"));
        WatchModeWindow = new WatchModeWindow(Root?.Q<VisualElement>("WatchModeWindow"));
        KessenWindow = new KessenWindow(Root?.Q<VisualElement>("KessenWindow"));
        SystemWindow = new SystemWindow(Root?.Q<VisualElement>("SystemWindow"));
        MessageWindow = new MessageWindow(Root?.Q<VisualElement>("MessageWindow"));
        DebugUIParent = Root?.Q<VisualElement>("DebugUIParent");
        WindowHost = Root?.Q<VisualElement>("WindowHost");
    }
}