//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class MainUI
{
    [SerializeField]
    private UIDocument _document;
    public VisualElement UIContainer { get; private set; }

    public Button buttonNextPhase { get; private set; }

    public Button buttonNextTurn { get; private set; }

    public Button buttonAuto { get; private set; }

    public Button buttonHold { get; private set; }

    public Button buttonToggleDebugUI { get; private set; }

    public VisualElement DebugUI { get; private set; }

    public BattleDialog BattleDialog { get; private set; }

    public SystemWindow SystemWindow { get; private set; }

    public VisualElement DebugUIParent { get; private set; }

    public VisualElement DialogHost { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        UIContainer = Root?.Q<VisualElement>("UIContainer");
        buttonNextPhase = Root?.Q<Button>("buttonNextPhase");
        buttonNextTurn = Root?.Q<Button>("buttonNextTurn");
        buttonAuto = Root?.Q<Button>("buttonAuto");
        buttonHold = Root?.Q<Button>("buttonHold");
        buttonToggleDebugUI = Root?.Q<Button>("buttonToggleDebugUI");
        DebugUI = Root?.Q<VisualElement>("DebugUI");
        BattleDialog = new BattleDialog(Root?.Q<VisualElement>("BattleDialog"));
        SystemWindow = new SystemWindow(Root?.Q<VisualElement>("SystemWindow"));
        DebugUIParent = Root?.Q<VisualElement>("DebugUIParent");
        DialogHost = Root?.Q<VisualElement>("DialogHost");
    }
}