//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class OrganizeScreen
{
    public CharacterTable CharacterTable { get; private set; }

    public CharacterInfo CharacterInfo { get; private set; }

    public Label labelTargetSalaryRatio { get; private set; }

    public Label labelTargetLoyalty { get; private set; }

    public Button buttonUp { get; private set; }

    public Button buttonDown { get; private set; }

    public Button buttonDecrease { get; private set; }

    public Button buttonIncrease { get; private set; }

    public Label labelDescription { get; private set; }

    public Button buttonClose { get; private set; }

    public VisualElement Root { get; }

    public OrganizeScreen(VisualElement root)
    {
        Root = root;
        CharacterTable = new CharacterTable(Root?.Q<VisualElement>("CharacterTable"));
        CharacterInfo = new CharacterInfo(Root?.Q<VisualElement>("CharacterInfo"));
        labelTargetSalaryRatio = Root?.Q<Label>("labelTargetSalaryRatio");
        labelTargetLoyalty = Root?.Q<Label>("labelTargetLoyalty");
        buttonUp = Root?.Q<Button>("buttonUp");
        buttonDown = Root?.Q<Button>("buttonDown");
        buttonDecrease = Root?.Q<Button>("buttonDecrease");
        buttonIncrease = Root?.Q<Button>("buttonIncrease");
        labelDescription = Root?.Q<Label>("labelDescription");
        buttonClose = Root?.Q<Button>("buttonClose");
    }
}