//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class RightPane
{
    [SerializeField]
    private UIDocument _document;
    public Label Label { get; private set; }

    public Label labelTerrain { get; private set; }

    public Label labelPosition { get; private set; }

    public Image imageCountryColor { get; private set; }

    public Label labelRulerName { get; private set; }

    public Label labelAreaCount { get; private set; }

    public Label labelTotalIncome { get; private set; }

    public Label labelTotalGold { get; private set; }

    public Label labelMemberCount { get; private set; }

    public Label labelSoldierCount { get; private set; }

    public Label labelTotalPower { get; private set; }

    public Image imageAllyCountryColor { get; private set; }

    public Label labelAlly { get; private set; }

    public Image imageRuler { get; private set; }

    public Label labelCharaStatus { get; private set; }

    public Label labelCharaName { get; private set; }

    public Label labelCharaAttack { get; private set; }

    public Label labelCharaDefence { get; private set; }

    public Label labelCharaIntelligence { get; private set; }

    public Label labelCharaLoyalty { get; private set; }

    public Label labelCharaPrestige { get; private set; }

    public Label labelCharaContribution { get; private set; }

    public Label labelCharaSalaryRatio { get; private set; }

    public VisualElement Soldiers { get; private set; }

    public VisualElement VisualElement { get; private set; }

    public Image imageChara { get; private set; }

    public VisualElement CellInformation { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        Label = Root?.Q<Label>("Label");
        labelTerrain = Root?.Q<Label>("labelTerrain");
        labelPosition = Root?.Q<Label>("labelPosition");
        imageCountryColor = Root?.Q<Image>("imageCountryColor");
        labelRulerName = Root?.Q<Label>("labelRulerName");
        labelAreaCount = Root?.Q<Label>("labelAreaCount");
        labelTotalIncome = Root?.Q<Label>("labelTotalIncome");
        labelTotalGold = Root?.Q<Label>("labelTotalGold");
        labelMemberCount = Root?.Q<Label>("labelMemberCount");
        labelSoldierCount = Root?.Q<Label>("labelSoldierCount");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        imageAllyCountryColor = Root?.Q<Image>("imageAllyCountryColor");
        labelAlly = Root?.Q<Label>("labelAlly");
        imageRuler = Root?.Q<Image>("imageRuler");
        labelCharaStatus = Root?.Q<Label>("labelCharaStatus");
        labelCharaName = Root?.Q<Label>("labelCharaName");
        labelCharaAttack = Root?.Q<Label>("labelCharaAttack");
        labelCharaDefence = Root?.Q<Label>("labelCharaDefence");
        labelCharaIntelligence = Root?.Q<Label>("labelCharaIntelligence");
        labelCharaLoyalty = Root?.Q<Label>("labelCharaLoyalty");
        labelCharaPrestige = Root?.Q<Label>("labelCharaPrestige");
        labelCharaContribution = Root?.Q<Label>("labelCharaContribution");
        labelCharaSalaryRatio = Root?.Q<Label>("labelCharaSalaryRatio");
        Soldiers = Root?.Q<VisualElement>("Soldiers");
        VisualElement = Root?.Q<VisualElement>("VisualElement");
        imageChara = Root?.Q<Image>("imageChara");
        CellInformation = Root?.Q<VisualElement>("CellInformation");
    }
}