//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class RightPane
{
    [SerializeField]
    private UIDocument _document;
    public Button buttonNextPhase { get; private set; }

    public Button buttonNextTurn { get; private set; }

    public Button buttonAuto { get; private set; }

    public Button buttonHold { get; private set; }

    public CountryInfo CountryInfo { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        buttonNextPhase = Root?.Q<Button>("buttonNextPhase");
        buttonNextTurn = Root?.Q<Button>("buttonNextTurn");
        buttonAuto = Root?.Q<Button>("buttonAuto");
        buttonHold = Root?.Q<Button>("buttonHold");
        CountryInfo = new CountryInfo(Root?.Q<VisualElement>("CountryInfo"));
    }
}