//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class RightPane
{
    [SerializeField]
    private UIDocument _document;
    public Label labelTerrain { get; private set; }

    public Label labelPosition { get; private set; }

    public Label labelRulerName { get; private set; }

    public Label labelAreaCount { get; private set; }

    public Label labelTotalIncome { get; private set; }

    public Label labelTotalGold { get; private set; }

    public Label labelMemberCount { get; private set; }

    public Label labelSoldierCount { get; private set; }

    public Label labelTotalPower { get; private set; }

    public Label labelAlly { get; private set; }

    public Image imageRuler { get; private set; }

    public VisualElement CellInformation { get; private set; }

    public Label Label { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        labelTerrain = Root?.Q<Label>("labelTerrain");
        labelPosition = Root?.Q<Label>("labelPosition");
        labelRulerName = Root?.Q<Label>("labelRulerName");
        labelAreaCount = Root?.Q<Label>("labelAreaCount");
        labelTotalIncome = Root?.Q<Label>("labelTotalIncome");
        labelTotalGold = Root?.Q<Label>("labelTotalGold");
        labelMemberCount = Root?.Q<Label>("labelMemberCount");
        labelSoldierCount = Root?.Q<Label>("labelSoldierCount");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        labelAlly = Root?.Q<Label>("labelAlly");
        imageRuler = Root?.Q<Image>("imageRuler");
        CellInformation = Root?.Q<VisualElement>("CellInformation");
        Label = Root?.Q<Label>("Label");
    }
}