//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class SaveDataListWindowListItem
{
    public Label Soldiers { get; private set; }

    public Label Years { get; private set; }

    public Label PlayerName { get; private set; }

    public Label SavedTime { get; private set; }

    public VisualElement CharacterImage { get; private set; }

    public VisualElement Root { get; }

    public SaveDataListWindowListItem(VisualElement root)
    {
        Root = root;
        Soldiers = Root?.Q<Label>("Soldiers");
        Years = Root?.Q<Label>("Years");
        PlayerName = Root?.Q<Label>("PlayerName");
        SavedTime = Root?.Q<Label>("SavedTime");
        CharacterImage = Root?.Q<VisualElement>("CharacterImage");
    }
}