//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class SelectScenarioWindow
{
    [SerializeField]
    private UIDocument _document;
    public Button Button { get; private set; }

    public Label Title { get; private set; }

    public Button Close { get; private set; }

    public VisualElement Body { get; private set; }

    public VisualElement Border { get; private set; }

    public VisualElement VisualElement { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        Button = Root?.Q<Button>("Button");
        Title = Root?.Q<Label>("Title");
        Close = Root?.Q<Button>("Close");
        Body = Root?.Q<VisualElement>("Body");
        Border = Root?.Q<VisualElement>("Border");
        VisualElement = Root?.Q<VisualElement>("VisualElement");
    }
}