//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class SoldierInfoLarge
{
    public Label labelLevel { get; private set; }

    public Label labelHp { get; private set; }

    public Image imageSoldier { get; private set; }

    public VisualElement Root { get; }

    public SoldierInfoLarge(VisualElement root)
    {
        Root = root;
        labelLevel = Root?.Q<Label>("labelLevel");
        labelHp = Root?.Q<Label>("labelHp");
        imageSoldier = Root?.Q<Image>("imageSoldier");
    }
}