//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class SystemWindow
{
    public Button buttonCloseSystemWindow { get; private set; }

    public Button buttonSave { get; private set; }

    public Button buttonChangeCharacter { get; private set; }

    public Button buttonGoToTitle { get; private set; }

    public VisualElement Root { get; }

    public SystemWindow(VisualElement root)
    {
        Root = root;
        buttonCloseSystemWindow = Root?.Q<Button>("buttonCloseSystemWindow");
        buttonSave = Root?.Q<Button>("buttonSave");
        buttonChangeCharacter = Root?.Q<Button>("buttonChangeCharacter");
        buttonGoToTitle = Root?.Q<Button>("buttonGoToTitle");
    }
}