//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class TitleSceneUI
{
    [SerializeField]
    private UIDocument _document;
    public Button buttonCloseApplication { get; private set; }

    public SaveDataListWindow SaveDataList { get; private set; }

    public VisualElement Windows { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        buttonCloseApplication = Root?.Q<Button>("buttonCloseApplication");
        SaveDataList = new SaveDataListWindow(Root?.Q<VisualElement>("SaveDataList"));
        Windows = Root?.Q<VisualElement>("Windows");
    }
}