//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class TitleSceneUI
{
    [SerializeField]
    private UIDocument _document;
    public Button StartGame { get; private set; }

    public Button OpenSeting { get; private set; }

    public Button OpenManual { get; private set; }

    public Button FinishApplication { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        StartGame = Root?.Q<Button>("StartGame");
        OpenSeting = Root?.Q<Button>("OpenSeting");
        OpenManual = Root?.Q<Button>("OpenManual");
        FinishApplication = Root?.Q<Button>("FinishApplication");
    }
}