//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class WatchModeWindow
{
    public Button buttonChangeCharacter { get; private set; }

    public VisualElement Root { get; }

    public WatchModeWindow(VisualElement root)
    {
        Root = root;
        buttonChangeCharacter = Root?.Q<Button>("buttonChangeCharacter");
    }
}